  
language:
    java

sudo:
    false
    
dist: trusty

jdk:
    - oraclejdk13

matrix:
    allow_failures:
        - jdk: oraclejdk13

script:
    - mvn test -B
    - "mvn cobertura:cobertura"

after_success:
    - bash <(curl -s https://codecov.io/bash)
